/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExecutionPropiertiesGUI.java
 *
 * Created on 09-feb-2010, 12:14:35
 */

package castadiva_gui;

/**
 *
 * @author alvaro
 */
public class ExecutionPropiertiesGUI extends javax.swing.JFrame {

    /** Creates new form ExecutionPropiertiesGUI */
    public ExecutionPropiertiesGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SourceFolderLabel = new javax.swing.JLabel();
        ResultsFolderLabel = new javax.swing.JLabel();
        RepetitionsLabel = new javax.swing.JLabel();
        SourceFoldetText = new javax.swing.JTextField();
        SourceFolderButton = new javax.swing.JButton();
        ResultsFolderText = new javax.swing.JTextField();
        ResultsFolderButton = new javax.swing.JButton();
        RepetitionsSpinner = new javax.swing.JSpinner();
        AcceptButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setTitle("Edit propierties");
        setAlwaysOnTop(true);

        SourceFolderLabel.setText("Source Folder");

        ResultsFolderLabel.setText("Results Folder");

        RepetitionsLabel.setText("Repetitions");

        SourceFoldetText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SourceFoldetTextActionPerformed(evt);
            }
        });

        SourceFolderButton.setText("Search...");

        ResultsFolderButton.setText("Search...");

        AcceptButton.setText("Accept");

        CancelButton.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SourceFolderLabel)
                    .addComponent(ResultsFolderLabel)
                    .addComponent(RepetitionsLabel))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AcceptButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CancelButton))
                            .addComponent(ResultsFolderText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(SourceFoldetText, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ResultsFolderButton)
                            .addComponent(SourceFolderButton)))
                    .addComponent(RepetitionsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SourceFolderLabel)
                    .addComponent(SourceFoldetText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SourceFolderButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResultsFolderLabel)
                    .addComponent(ResultsFolderText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResultsFolderButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RepetitionsLabel)
                    .addComponent(RepetitionsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AcceptButton)
                    .addComponent(CancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SourceFoldetTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SourceFoldetTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SourceFoldetTextActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel RepetitionsLabel;
    private javax.swing.JSpinner RepetitionsSpinner;
    private javax.swing.JButton ResultsFolderButton;
    private javax.swing.JLabel ResultsFolderLabel;
    private javax.swing.JTextField ResultsFolderText;
    private javax.swing.JButton SourceFolderButton;
    private javax.swing.JLabel SourceFolderLabel;
    private javax.swing.JTextField SourceFoldetText;
    // End of variables declaration//GEN-END:variables

}
