/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExecutionPropiertiesDialog.java
 *
 * Created on 11-feb-2010, 12:02:14
 */

package castadiva_gui;

import castadiva.TrafficRecords.ExecutionRecord;
import java.awt.event.ActionListener;

/**
 *
 * @author alvaro
 */
public class ExecutionPropiertiesDialog extends javax.swing.JDialog {
    int selected;

    /** Creates new form ExecutionPropiertiesDialog */
    public ExecutionPropiertiesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public ExecutionPropiertiesDialog(java.awt.Frame parent, boolean modal, Integer selected) {
        super(parent, modal);
        initComponents();
        ExecutionPlannerGUI m_exec = (ExecutionPlannerGUI) parent;
        ExecutionRecord exe = m_exec.getRow(selected);
        this.selected = selected;
        this.SourceFoldetText.setText(exe.getSourceFolder());
        this.ResultsFolderText.setText(exe.getResultsFolder());
        this.RepetitionsSpinner.setValue(exe.getRuns());

    }

    public Integer getSelectedRow() {
        return selected;
    }

    public String getSourceText() {
        return this.SourceFoldetText.getText();
    }

    public String getResultsText() {
        return this.ResultsFolderText.getText();
    }

    public void setSourceText(String text){
        this.SourceFoldetText.setText(text);
    }

    public void setResultsText(String text) {
        this.ResultsFolderText.setText(text);
    }

    public Integer getRuns() {
        return (Integer) this.RepetitionsSpinner.getValue();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ResultsFolderLabel = new javax.swing.JLabel();
        SourceFolderLabel = new javax.swing.JLabel();
        AcceptButton = new javax.swing.JButton();
        ResultsFolderText = new javax.swing.JTextField();
        SourceFolderButton = new javax.swing.JButton();
        SourceFoldetText = new javax.swing.JTextField();
        RepetitionsLabel = new javax.swing.JLabel();
        RepetitionsSpinner = new javax.swing.JSpinner();
        ResultsFolderButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setTitle("Edit propierties");

        ResultsFolderLabel.setText("Results Folder");

        SourceFolderLabel.setText("Source Folder");

        AcceptButton.setText("Accept");

        SourceFolderButton.setText("Search...");

        SourceFoldetText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SourceFoldetTextActionPerformed(evt);
            }
        });

        RepetitionsLabel.setText("Repetitions");

        ResultsFolderButton.setText("Search...");

        CancelButton.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SourceFolderLabel)
                    .addComponent(ResultsFolderLabel)
                    .addComponent(RepetitionsLabel))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AcceptButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CancelButton))
                            .addComponent(ResultsFolderText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(SourceFoldetText, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ResultsFolderButton)
                            .addComponent(SourceFolderButton)))
                    .addComponent(RepetitionsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 201, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SourceFolderLabel)
                    .addComponent(SourceFoldetText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SourceFolderButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResultsFolderLabel)
                    .addComponent(ResultsFolderText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResultsFolderButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RepetitionsLabel)
                    .addComponent(RepetitionsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AcceptButton)
                    .addComponent(CancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SourceFoldetTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SourceFoldetTextActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_SourceFoldetTextActionPerformed

    /**
    * @param args the command line arguments
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel RepetitionsLabel;
    private javax.swing.JSpinner RepetitionsSpinner;
    private javax.swing.JButton ResultsFolderButton;
    private javax.swing.JLabel ResultsFolderLabel;
    private javax.swing.JTextField ResultsFolderText;
    private javax.swing.JButton SourceFolderButton;
    private javax.swing.JLabel SourceFolderLabel;
    private javax.swing.JTextField SourceFoldetText;
    // End of variables declaration//GEN-END:variables


    /*************************************
     *              LISTENERS            *
     *************************************/
    public void addCancelButtonListener(ActionListener a) {
        CancelButton.addActionListener(a);
    }

    public void addAcceptButtonListener(ActionListener a) {
        AcceptButton.addActionListener(a);
    }

    public void addSourceFolderButton(ActionListener a){
        SourceFolderButton.addActionListener(a);
    }

    public void addResultsFolderButton(ActionListener a) {
        ResultsFolderButton.addActionListener(a);
    }
}
